#pragma once
#include <DXGIFormat.h>

#define SHARED_SURFACE_COPY_SIZE 16

typedef struct SHARED_SURFACE_QUEUE_DESC
{
    UINT Width;
    UINT Height;
    DXGI_FORMAT Format;
    UINT NumSurfaces;
    UINT MetaDataSize;
    DWORD Flags;
} SHARED_SURFACE_QUEUE_DESC;

typedef struct SHARED_SURFACE_QUEUE_CLONE_DESC
{
    UINT MetaDataSize;
    DWORD Flags;
} SHARED_SURFACE_QUEUE_CLONE_DESC;

typedef enum SURFACE_QUEUE_FLAG
{
    SURFACE_QUEUE_FLAG_DO_NOT_WAIT = 0x1L,
    SURFACE_QUEUE_FLAG_SINGLE_THREADED = 0x2L,
} SURFACE_QUEUE_FLAG;

enum SharedDXGISurfaceState
{
    SHARED_DXGI_SURFACE_STATE_UNINITIALIZED = 0,
    SHARED_DXGI_SURFACE_STATE_DEQUEUED = 1,
    SHARED_DXGI_SURFACE_STATE_ENQUEUED = 2,
    SHARED_DXGI_SURFACE_STATE_FLUSHED = 3,
};